def x(x):
  return round(float(x)*1.2+y/7)
  #This return statement is the backbone of the entire function, and was created by me
event=input("You are using this program because there has been an event that has resulted in someone not having to pay. What is the event?  ")
print("Enter each person's bill with no $ or cent sign. Decimals can be used")
special=input("Who is the person who does not have to pay?:    ")
y = float(input(special +"'s bill:  "))
#This is not like the others, as it actually is a y instead of an x. This lets me assign this variable to a new area such as division.
name1=input("What is the next persons name?  ")
number1 = input(name1 +"s bill:  ")
name2=input("What is the next persons name?  ")
number2 = input(name2 +"s bill:  ")
name3=input("What is the next persons name?  ")
number3 = input(name3 +"s bill:  ")
name4=input("What is the next persons name?  ")
number4 = input(name4 +"s bill:  ")
name5=input("What is the next persons name?  ")
number5 = input(name5 +"s bill:  ")
name6=input("What is the next persons name?  ")
number6 = input(name6 +"s bill:  ")
name8 = input("What is the next persons name?  ")
number8 = input(name8 +"s bill:  ")
print(event)
print(name1)
print(x(number1))
print(name2)
print(x(number2))
print(name3)
print(x(number3))
print(name4)
print(x(number4))
print(name5)
print(x(number5))
print(name6)
print(x(number6))
print(name8)
print(x(number8))